### ISSUE TITLE
Vertical ruler gets translated when scrolling editor horizontally

### ISSUE THREAD

**Issue by GhassenRjab** [forgecrafted/rulerz#24] opened 2017-07-20 08:08 UTC
Before scrolling horizontally the vertical ruler is in the right position :
![image](https://user-images.githubusercontent.com/6123547/28407058-aca63704-6d2a-11e7-974b-5910de72cde6.png)
But when I scroll the editor horizontally the ruler gets translated as I am scrolling :
![image](https://user-images.githubusercontent.com/6123547/28407104-d5d395a4-6d2a-11e7-8938-4d6ecffe98da.png)

**Comment by cmtonkinson** [comment] 2017-07-24 20:25
Thanks for using rulerz, and caring enough to submit a bug report! We're no longer actively using Atom day-to-day, and so haven't devoted a great deal of time to the package. If you're interested in picking up maintainership, please let me know.

**Comment by GhassenRjab** [comment] 2017-07-24 20:48
I'll fork the project and try to create a PR fixing this issue first

**Comment by chmac** [comment] 2018-03-21 14:05
@GhassenRjab Feel free to whip up a PR. I can't reproduce this issue on my machine, so will close this issue now. Feel free to reopen if you still have the problem.

**Closed as completed by chmac** 2018-03-21 14:05 UTC
