### ISSUE TITLE
Failed to activate the rulerz package

### ISSUE THREAD

**Issue by shuriktm** [forgecrafted/rulerz#8] opened 2015-06-05 12:39 UTC
With Atom v0.206.0 deprecated APIs are disabled.
And now I get an exception when open Atom.

**Atom Version**: 0.206.0
**System**: Unknown Windows Version
**Thrown From**: [rulerz](https://github.com/forgecrafted/rulerz) package, v0.2.7
### Stack Trace

Failed to activate the rulerz package

```
At Cannot read property 'appendChild' of undefined

TypeError: Cannot read property 'appendChild' of undefined
    at ruler-view.RulerView.insert (C:\Users\Alexander\.atom\packages\rulerz\lib\ruler-view.coffee:36:24)
    at ruler-view.RulerView.initialize (C:\Users\Alexander\.atom\packages\rulerz\lib\ruler-view.coffee:27:12)
    at Object.createView (C:\Users\Alexander\.atom\packages\rulerz\lib\ruler-manager.coffee:25:32)
    at ViewRegistry.module.exports.ViewRegistry.createView (C:\Users\Alexander\AppData\Local\atom\app-0.206.0\resources\app.asar\src\view-registry.js:74:72)
    at ViewRegistry.module.exports.ViewRegistry.getView (C:\Users\Alexander\AppData\Local\atom\app-0.206.0\resources\app.asar\src\view-registry.js:61:21)
    at CursorModel.module.exports.CursorModel.initialize (C:\Users\Alexander\.atom\packages\rulerz\lib\cursor-model.coffee:25:25)
    at new CursorModel (C:\Users\Alexander\.atom\packages\rulerz\lib\cursor-model.coffee:20:12)
    at C:\Users\Alexander\.atom\packages\rulerz\lib\ruler-manager.coffee:33:20
    at TextEditor.module.exports.TextEditor.observeCursors (C:\Users\Alexander\AppData\Local\atom\app-0.206.0\resources\app.asar\src\text-editor.js:350:9)
    at C:\Users\Alexander\.atom\packages\rulerz\lib\ruler-manager.coffee:32:49
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "tomorrow-syntax"
    ],
    "disabledPackages": [
      "status-tab-spacing",
      "autocomplete-paths",
      "autocomplete-emojis",
      "open-last-project",
      "tab-control",
      "tab-rename",
      "atom-fuzzy-grep"
    ]
  },
  "rulerz": {}
}
```
### Installed Packages

``` coffee
# User
aligner-css, v1.2.0
aligner-php, v1.0.0
block-cursor, v0.12.5
color-picker, v2.0.4
compare-files, v0.4.1
custom-invisibles, v0.1.2
custom-title, v1.0.1
docblockr, v0.7.2
file-icons, v1.5.7
highlight-selected, v0.9.3
linter, v0.12.6
linter-coffeelint, v0.3.1
linter-htmlhint, v0.0.16
linter-jshint, v0.1.6
linter-xmllint, v0.0.6
live-archive, v0.1.15
local-history, v3.2.2
minimap, v4.9.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
minimap-selection, v4.2.0
package-manager-commands, v2.0.3
project-manager, v1.15.8
rulerz, v0.2.7
sync-settings, v0.2.2
tabs-to-spaces, v0.11.0
tag, v0.3.0
toggle-slash, v1.0.11
tomorrow-syntax, v0.2.0
trailing-spaces, v0.3.0
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by cmtonkinson** [comment] 2015-06-05 13:17
Thanks for the report; when 206 lands for me officially I'll take another look but I just loaded it from git and was unable to reproduce.

**Comment by JohnMurga** [comment] 2015-06-05 16:51
I submitted a pull request that solves the issue for me ...
I am not sure why the underlayer is not being created in Atom 206, but it happens for me also

**Comment by cmtonkinson** [comment] 2015-06-06 01:22
Thanks @JohnMurga, I'll take a look when I get back to my office.

**Comment by cmtonkinson** [comment] 2015-06-10 15:36
@JohnMurga doesn't seem as if this alone does the trick; I'm looking into it now (having manually upgraded to 208)

**Comment by JohnMurga** [comment] 2015-06-10 15:46
This is a different issue to #10 ...
The pull request fixed it on 207 (I have it on one machine).
On 208 the underlayer does not display at all which is a different issue that affects other packages.

**Comment by cmtonkinson** [comment] 2015-06-12 03:00
Re-closing, as rulerz needs to be reworked at a more fundamental level because of the underlayer removal that @JohnMurga notes in v0.208. Shifting full discussion completely to #10.

**Closed as completed by cmtonkinson** 2015-06-12 03:00 UTC

**Comment by cmtonkinson** [comment] 2015-06-12 16:12
Just an update @shuriktm, rulerz has been modified to work with v0.209 and, hopefully, 1.0 moving forward. Thanks for your help!

**Comment by shuriktm** [comment] 2015-06-13 17:07
Thanks for the quick fix @cmtonkinson, it works for me now.
